missing include in logging.h
The logging.h file declares functions with return type
`std::filesystem::path`, which is declared in standard header file
<filesystem>. However, logging.h doesn't include this header file, the
sisl library user sees too many compile errors like this:

error: ‘path’ in namespace ‘std::filesystem’ does not name a type

Even when the application src file doesn't directly include logging.h
we still see this error because we might use other sisl components,
which includes this logging.h indirectly.

To relief the user application, we should include <filesystem> in
logging.h